---
title: "Andy's CV"
---

<https://www.linkedin.com/in/zhangfanhuang/>

**Zhangfan (Andy) Huang**

(469)-441-2055;   zhangfanhuang\@hotmail.com                                                

**EDUCATION**

**Dallas Baptist University                                                                                                                                        ﻿(GPA: 3.78/4.0)** *M.B.A. (Business Intelligence and Analytics)                                                                                                      Jan 2020 - May 2022*

﻿Core Courses: System Analysis & Project Management, Business Data Warehousing, Cloud Computing, Python, Data

Visualization, Business Intelligence & Data Mining.

**The University of Texas at Dallas                                                                                                                          (GPA: 3.33/4.0)** *M.S., Supply Chain Management                                                                                                                        Aug 2015 - May 2017*

*M.S., Finance                                                                                                                                            Aug 2014 - Dec 2016*

*Core Courses: Statistics, Operation Management, Purchase Source & Contract Management, Global Logistics and*

*Transportation, Quality Control Lean Six Sigma, Global Supply Chain Management, Engineering Packaged Goods*

*Distribution, Flexible Manufacturing Strategy.*

**Guangdong University of Finance, Guangzhou, China                                                                                   ﻿(GPA: 3.50/4.0)**       \
*B.S., Finance                                                                                                                                                              Sep 2010 - Jun 2014*

**WORKING EXPERIENCE**

**JY Tec Supply Inc, Irving, Texas**                                                                                                         August 2021 – August 2024

*Procurement Specialist*                      

·       Coordinated with major freight packaging and shipping cargos to Hong Kong worth more than ten million dollars

·       Visited, evaluated, and negotiated with suppliers; ensured that products were delivered in a timely manner and that the quality of the goods received was satisfactory.

·       During the R2 Stage 1 and Stage 2 certification process set up and did preliminary tests for Reception, Testing, Distribution, and Quality Control sections of the warehouse.

·       Worked with the managers to coordinate bidding efforts with major carriers such as Verizon, AT&T, and T-Mobile, etc.

**Massimo Motor Sports, Garland, Texas**                                                                September 2020 – August 2021

*Operation Specialist*                      

·       Negotiated purchasing price with 10+ international suppliers for 1500+ products on monthly basis and saved \$120,000 in 2020 Q4 based on order quantity and currency exchange rate.

·       Forecasted quarterly demand for seasonal and non-seasonal products by historical data and communicated with sales team to minimize out of stock or over stock weekly.

·       Arranged and allocated weekly payment to vendors by terms with approval from CFO.

·       Prepared Import documentation and coordinated with Custom Clearance companies and Logistics Companies.

**Industrial and Commercial Bank of China, Shenzhen, China**                                                May 2018 – December 2019

*Account Manager (Shenzhen Huaqiang Branch)*                            

·       Sold Insurance products for 80,000 USD and AIP(Automatic Investment Plan) for 100,000 USD which is 112% of the sale target.

·       Contributed in marketing Bank Financial Products Sales for 50 million USD with Huaqiangbei major clients.

·       Referred and sold ICBC credit cards over 500 in internet marketing and promotions, ranked top 3 in ICBC system.

**ACADEMIC ORGANIZATIONS**

﻿Information Technology Management Ambassador Association, DBU                                              January 2020 – May 2020

Supply Chain Leadership Council, UT Dallas                                                                 September 2015 – May 2017

Financial Leadership Association, UT Dallas                                                             September 2014 – May 2017**\
\
**

**ADDITIONAL INFORMATION**

*Technical: Proficient in Excel, PowerPoint, Word, Access, Python, R, Bloomberg, Capital IQ, QuickBooks, Tableau, MySQL.*
